on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: windows-2019
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5

        - name: Navigate to Workspace
          run: cd $GITHUB_WORKSPACE

        - name: Get version
          id: versionReader
          run: |
            set /p Version=<Version.txt
            echo ::set-output name=VERSION::%Version%

        - name: Restore Packages
          run: nuget restore DU-Industry-Tool.sln

        - name: Build Solution
          run: |
            msbuild.exe DU-Industry-Tool.sln /p:platform="Any CPU" /p:configuration="Release"

        - name: Archive Release
          uses: thedoctor0/zip-release@main
          with:
             path: DU-Industry-Tool/bin/Release/
             type: 'zip'
             filename: DU-Industry-Tool${{steps.versionReader.outputs.VERSION}}.zip
             exclusions: '*.git* /*node_modules/* *.vs* *.user .editorconfig'

        - name: Create github Release
          id: create_release
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: v${{ steps.versionReader.outputs.VERSION }}
              release_name: DU-Industry-Toolv${{ steps.versionReader.outputs.VERSION }}
              draft: true
              prerelease: false
        - name: Upload release
          uses: actions/upload-release-asset@v1.0.1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: DU-Industry-Tool${{steps.versionReader.outputs.VERSION}}.zip
              asset_name: DU-Industry-Tool${{steps.versionReader.outputs.VERSION}}.zip
              asset_content_type: application/zip
        - name: Publish release
          uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}
