on:
    push:
        branches:
            - master
        paths-ignore:
            - '.github/**/*.yml'
            - '.git*'
            - '.vscode'

jobs:
    build:
        runs-on: windows-2019
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.6

        - name: Navigate to Workspace
          run: cd $GITHUB_WORKSPACE

        - name: Get Assembly Version
          id: getversion
          uses: berglie/assembly-version/get@v1
          with:
            filename: 'Version.txt'
            directory: '.'

        - name: Bump version and push tag
          id: tag_version
          uses: earldata/create-semver-tags-action@main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Generate Changelog
          id: changelog
          uses: jaywcjlove/changelog-generator@main
          with:
            head-ref: ${{ steps.tag_version.outputs.new_tag }}
            filter-author: (tobitege|Dimencia)
            filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

        - name: Restore Packages
          run: nuget restore DU-Industry-Tool.sln

        - name: Build Solution
          run: |
            msbuild.exe DU-Industry-Tool.sln /p:platform="Any CPU" /p:configuration="Release"

        - name: Release Notes
          id: release_notes
          uses: suzuito/create-release-by-file@master
          with:
            release_note: ./changelog.md
            prefix: '# '
            check_only: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Archive Release
          uses: thedoctor0/zip-release@main
          with:
            directory: DU-Industry-Tool/bin/Release/
            type: 'zip'
            filename: DU-Industry-Tool-v${{ steps.tag_version.outputs.new_tag }}.zip
            exclusions: '*.git* /*node_modules/* *.exe.config *.xml *.pdb *.vs* *.user .editorconfig'

        - name: Create github Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v${{ steps.tag_version.outputs.new_tag }}
            release_name: DU-Industry-Tool-v${{ steps.tag_version.outputs.new_tag }}
            draft: true
            prerelease: false

        - name: Upload release
          uses: actions/upload-release-asset@v1.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: DU-Industry-Tool/bin/Release/DU-Industry-Tool-v${{ steps.tag_version.outputs.new_tag }}.zip
            asset_name: DU-Industry-Tool-v${{ steps.tag_version.outputs.new_tag }}.zip
            asset_content_type: application/zip

        - name: Publish release
          uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}
